
install: network_display_event.py pygame_midi_wrapper.py

network_display_event.py:
	curl https://raw.githubusercontent.com/calaldees/PentatonicHero/master/network_display_event.py --compressed -O
pygame_midi_wrapper.py:
	curl https://raw.githubusercontent.com/calaldees/PentatonicHero/master/network_display_event.py --compressed -O
music.py:
	curl https://raw.githubusercontent.com/calaldees/PentatonicHero/master/music.py --compressed -O

run:
	python3 displaytrigger.py
