version: '3.6'

services:

  subscriptionserver:
    image: superlimitbreak/subscriptionserver:latest
    build:
      context: ${ROOT_FOLDER}/multisocketServer/multisocketServer/server
    ports:
      - ${PORT_TCP}:${PORT_TCP}
      - ${PORT_WEBSOCKET}:${PORT_WEBSOCKET}
    #command: ["--tcp_port", "9872", "--websocket_port", "9873", "--log_level", "0"]  # For debugging to view messages

  subscriptionserver_bridge:
    image: superlimitbreak/subscriptionserver_bridge:latest
    build:
      context: ${ROOT_FOLDER}/multisocketServer/webBridge
    ports:
      - ${PORT_URL_WEBSOCKET_BRIDGE}:${PORT_URL_WEBSOCKET_BRIDGE}
    links:
      - subscriptionserver
    command: [
      '--port', '${PORT_URL_WEBSOCKET_BRIDGE}',
      '--subscription_server_hostname', 'multisocket_subscription_server:${PORT_TCP}',
    ]
    #healthcheck:
    #  test: ["CMD-SHELL", "netstat -an | grep ${PORT_URL_WEBSOCKET_BRIDGE} > /dev/null; if [ 0 != $? ]; then exit 1; fi;"]

  mediainfoservice:
    image: superlimitbreak/mediainfoservice:latest
    build:
      context: ${ROOT_FOLDER}/mediaInfoService
    volumes:
      - ${PATH_HOST_media}:/srv/media:ro
    ports:
      - 8331:8331
    command: /srv/media --port 8331

  nginx:
    image: nginx:alpine
    env_file:
        - .env
    ports:
      - "${PORT_NGINX}:80"
    volumes:
      #- ./nginx.conf:/tmp/nginx.conf:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./root:/srv/root:ro
      - ${PATH_HOST_media}:/srv/media:ro
      - ${PATH_HOST_eventmap}:/srv/eventmap:ro
      - ${PATH_HOST_displayconfig}:/srv/displayconfig:ro
      - ${PATH_HOST_trigger}:/srv/trigger:ro
      - ${PATH_HOST_display}:/srv/display:ro
      - ${PATH_HOST_stageViewer}:/srv/stageViewer:ro
      - ${PATH_HOST_stageconfig}:/srv/stageconfig:ro
      - ${PATH_HOST_stageOrchestration}:/srv/stageOrchestration:ro
      - ${PATH_HOST_webMidiTools}:/srv/webMidiTools:ro
    links:
      - mediainfoservice
      - subscriptionserver_bridge
    #command: /bin/sh -c "DOLLAR='$$' envsubst < /tmp/nginx.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    #healthcheck:
    #  test: curl --fail -s http://localhost:5000/ || exit 1
    #  interval: 1m30s
    #  timeout: 10s
    #  retries: 3