version: '3.6'

services:

  multisocket_subscription_server:
    build:
      context: ${PATH_LIB_CALALDESS}/multisocket/
      dockerfile: subscription_server.dockerfile
    ports:
      - ${PORT_TCP}:${PORT_TCP}
      - ${PORT_WEBSOCKET}:${PORT_WEBSOCKET}

  multisocket_url_to_subscription_bridge:
    build:
      context: ${PATH_LIB_CALALDESS}/net/
      dockerfile: falcon_url_to_subscription_bridge.dockerfile
    ports:
      - ${PORT_URL_WEBSOCKET_BRIDGE}:${PORT_URL_WEBSOCKET_BRIDGE}
    links:
      - multisocket_subscription_server
    command: --port ${PORT_URL_WEBSOCKET_BRIDGE} --subscription_server_hostname multisocket_subscription_server:${PORT_TCP}
    #healthcheck:
    #  test: ["CMD-SHELL", "netstat -an | grep ${PORT_URL_WEBSOCKET_BRIDGE} > /dev/null; if [ 0 != $? ]; then exit 1; fi;"]

  nginx:
    image: nginx:mainline-alpine
    environment:
      - PORT_NGINX
      - PATH_HOST_media
    env_file:
        - .env
    ports:
      - "${PORT_NGINX}:${PORT_NGINX}"
    volumes:
      - ./nginx.conf:/tmp/nginx.conf:ro
      - ./root:${PATH_CONTAINER_ROOT}:ro
      - ${PATH_HOST_media}:${PATH_HOST_media}:ro
      - ${PATH_HOST_eventmap}:${PATH_CONTAINER_eventmap}:ro
      - ${PATH_HOST_displayconfig}:${PATH_CONTAINER_displayconfig}:ro
      - ${PATH_HOST_trigger}:${PATH_CONTAINER_trigger}:ro
      - ${PATH_HOST_display}:${PATH_CONTAINER_display}:ro
      - ${PATH_HOST_stageViewer}:${PATH_CONTAINER_stageViewer}:ro
      - ${PATH_HOST_stageOrchestration}:${PATH_CONTAINER_stageOrchestration}:ro
      - ${PATH_HOST_webMidiTools}:${PATH_CONTAINER_webMidiTools}:ro
    links:
      - multisocket_url_to_subscription_bridge
    command: /bin/sh -c "DOLLAR='$$' envsubst < /tmp/nginx.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    #healthcheck:
    #  test: curl --fail -s http://localhost:5000/ || exit 1
    #  interval: 1m30s
    #  timeout: 10s
    #  retries: 3