help:
	# todo

install:
	# todo

run: install
	# todo

test:
	todo

screen_size:
	curl -XGET http://localhost:6543/event/screen_size.set -d '{"deviceid": "main", "top":"100px", "left":"100px", "width": "400px", "height":"300px", "border": "1px dashed green"}'